name: web_lab
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_for_web: ^1.0.0
  flutter_for_web_ui: ^1.0.0
  image: ^2.1.4
  # flutter_markdown: ^0.2.0
  # cloud_firestore: ^0.12.9+1
  # shared_preferences: ^0.5.3+4

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
